_wandb:
    value:
        cli_version: 0.18.3
        code_path: code/train.py
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 2
                - 3
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
Adam_eps:
    value: 0.00015
alg:
    value: rrd_mujoco_pytorch_xql
alpha:
    value: 0.9
chi2_coeff:
    value: 0.20000000298023224
double:
    value: false
dueling:
    value: false
env:
    value: Ant-v2
polyak:
    value: 0.9950000047683716
q_lr:
    value: 0.0003000000142492354
rrd_batch_size:
    value: 256
rrd_bias_correction:
    value: true
rrd_sample_size:
    value: 64
train_batches:
    value: 100
