wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/algorithm/sac_rrd_iq.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1740977773.624458
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.20
      5: 0.13.11
      8:
      - 6
alpha:
  desc: null
  value: 0.2
autotune:
  desc: null
  value: true
batch_size:
  desc: null
  value: 512
buffer_size:
  desc: null
  value: 2000
capture_video:
  desc: null
  value: false
cuda:
  desc: null
  value: true
env_id:
  desc: null
  value: Ant-v4
exp_name:
  desc: null
  value: sac_rrd_iq
gamma:
  desc: null
  value: 0.99
learning_starts:
  desc: null
  value: 5000.0
policy_frequency:
  desc: null
  value: 2
policy_lr:
  desc: null
  value: 0.0003
q_coefficient:
  desc: null
  value: 1
q_lr:
  desc: null
  value: 0.001
r_coefficient:
  desc: null
  value: 0.02
seed:
  desc: null
  value: 1
target_network_frequency:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 3000000
track:
  desc: null
  value: true
trajectory_size:
  desc: null
  value: 1000
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: cleanRL
